<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>beheersysteem_uitvaartcentrum.backend.application</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.9.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\beheersysteem-uitvaartcentrum.backend.domain\beheersysteem-uitvaartcentrum.backend.domain.csproj" />
	</ItemGroup>
</Project>